#!/usr/bin/env python
# -*- coding: utf-8 -*-

import shelve, sys, dbus

MM_DBUS_SERVICE='org.freedesktop.ModemManager'
MM_DBUS_INTERFACE_MODEM_GSM_NETWORK='org.freedesktop.ModemManager.Modem.Gsm.Network'

mm_reg = { 0: "inactive",
           1: "own_network",
           2: "searching",
           3: "forbidden",
           4: "unknown",
           5: "roaming"
         }

bus = dbus.SystemBus()
objpath = sys.argv[1]
if objpath[:1] != '/':
    objpath = "/org/freedesktop/ModemManager/Modems/%s" % str(objpath)
proxy = bus.get_object(MM_DBUS_SERVICE, objpath)

# Properties
props = dbus.Interface(proxy, dbus_interface='org.freedesktop.DBus.Properties')
net = dbus.Interface(proxy, dbus_interface=MM_DBUS_INTERFACE_MODEM_GSM_NETWORK)

try:
	reg = net.GetRegistrationInfo()
	print mm_reg[int(reg[0])]
except dbus.exceptions.DBusException:
	sys.exit(1)