#!/usr/bin/python
# -*- Mode: python; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details:
#
# Copyright (C) 2009 - 2010Red Hat, Inc.
#

import sys, dbus, shelve

DBUS_INTERFACE_PROPERTIES='org.freedesktop.DBus.Properties'
MM_DBUS_SERVICE='org.freedesktop.ModemManager'
MM_DBUS_INTERFACE_MODEM='org.freedesktop.ModemManager.Modem'
MM_DBUS_INTERFACE_MODEM_GSM_NETWORK='org.freedesktop.ModemManager.Modem.Gsm.Network'

gsm_act =     { 0: "(GSM)",
                1: "(GSM Compact)",
                2: "(UMTS)",
                3: "(EDGE)",
                4: "(HSDPA)",
                5: "(HSUPA)",
                6: "(HSPA)"
              }

bus = dbus.SystemBus()
objpath = sys.argv[1]
if objpath[:1] != '/':
    objpath = "/org/freedesktop/ModemManager/Modems/" + str(objpath)
proxy = bus.get_object(MM_DBUS_SERVICE, objpath)

# Properties
props = dbus.Interface(proxy, dbus_interface='org.freedesktop.DBus.Properties')

mtype = props.Get(MM_DBUS_INTERFACE_MODEM, 'Type')
if mtype == 2:
    sys.exit(1)

net = dbus.Interface(proxy, dbus_interface=MM_DBUS_INTERFACE_MODEM_GSM_NETWORK)

try:
    results = net.Scan(timeout=120)
except dbus.exceptions.DBusException, e:
    results = {}

for r in results:
    status = r['status']
    if status == "1":
        status = "Disponibile"
    elif status == "2":
        status = "Connesso"
    elif status == "3":
        status = "Accesso negato"
    else:
        status = "Sconosciuto"

    access_tech = ""
    try:
        access_tech_num = int(r['access-tech'])
        access_tech = gsm_act[access_tech_num]
    except KeyError:
        pass

    opnum = r['operator-num']

    mcc = int(opnum[:3])
    mnc = int(opnum[3:])

    shelf = shelve.open("/usr/local/share/zengsm/operators", "r")
    operators = shelf["operators"]

    if r.has_key('operator-long') and len(r['operator-long']):
        print "Nome: {0}\nID: {1} {2}\nStato: {3} {4}\n\n".format(r['operator-long'], opnum, operators[mcc][mnc][:-1].__repr__().replace("[", "(").replace("]", ")").replace("\"", "\\\""), status, access_tech),
    elif r.has_key('operator-short') and len(r['operator-short']):
        print "Nome: {0}\nID: {1} {2}\nStato: {3} {4}\n\n".format(r['operator-short'], opnum, operators[mcc][mnc][:-1].__repr__().replace("[", "(").replace("]", ")").replace("\"", "\\\""), status, access_tech),
    else:
        print "ID: {0} {1}\nStato: {2} {3}\n\n".format(opnum, operators[mcc][mnc][:-1].__repr__().replace("[", "(").replace("]", ")").replace("\"", "\\\""), status, access_tech),